import Link from "next/link";
import "./globals.css";

import { Inter } from "next/font/google";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

   
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className="border-b p-6">
            <p className="text-4xl font-bold"> Marketplace</p>
             <div className="flex mt-4">
              <Link href="/" className="mr-6 text-pink-500">
                Home
              </Link>
              <Link href="/create-nft" className="mr-6 text-pink-500">
                Sell NFT
              </Link>
              <Link href="/my-nfts" className="mr-6 text-pink-500">
                My NFTs
              </Link>
              <Link href="/dashboard" className="mr-6 text-pink-500">
                Dashboard
              </Link>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
